const data = {
  products: [
    {
      name: 'On the Essence of Chassidus',
      slug: 'on-the-essence-of-chassidus',
      category: 'Chassidus',
      image: '/images/chas1.jpg',
      price: 4,
      publisher: 'Kehot',
      condition: 'new',
      countInStock: 6,
      rating: 4.5,
      numReviews: 12,
      description: 'very well written',
    },
    {
      name: 'On the Essence of Chassidus',
      slug: 'on-the-essence-of-chassidus',
      category: 'Chassidus',
      image: '/images/chas1.jpg',
      price: 4,
      publisher: 'Kehot',
      condition: 'new',
      countInStock: 6,
      rating: 4.5,
      numReviews: 12,
      description: 'very well written',
    },
    {
      name: 'My Rebbe (Hebrew)',
      slug: 'my-rebbe-hebrew',
      category: 'Chassidic Thought',
      image: '/images/Rebbe1.jpg',
      price: 3,
      publisher: 'Magid',
      condition: 'new',
      countInStock: 9,
      rating: 4.5,
      numReviews: 12,
      description: 'very well written',
    },
    {
      name: 'My Rebbe (Hebrew)',
      slug: 'my-rebbe-hebrew',
      category: 'Chassidic Thought',
      image: '/images/Rebbe1.jpg',
      price: 4,
      publisher: 'Magid',
      condition: 'new',
      countInStock: 4,
      rating: 4.5,
      numReviews: 12,
      description: 'very well written',
    },
    {
      name: 'My Rebbe (Hebrew)',
      slug: 'my-rebbe-hebrew',
      category: 'Chassidic Thought',
      image: '/images/Rebbe1.jpg',
      price: 9,
      countInStock: 7,
      publisher: 'Magid',
      condition: 'new',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
